global:
  scrape_interval: 5s # Har 5 second baad data check karo

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] # Yeh Prometheus ko bolay ga ke khud ko monitor kare